=== dfornika/facsimile/conf/conf.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT configuration (input,output,bindings,form)>
<!ELEMENT input (ontology,imports?)>
<!ELEMENT ontology (#PCDATA)>
<!ELEMENT output (file,cssstyle)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT cssstyle (#PCDATA)>
<!ELEMENT imports (ontology*)>
<!ELEMENT bindings (classBindings,propertyBindings,questionTypeBindings)>
<!ELEMENT classBindings (binding*)>
<!ELEMENT propertyBindings (binding*)>
<!ELEMENT questionTypeBindings (binding*)>
<!ELEMENT binding (#PCDATA)>
<!ELEMENT form (iri,section+)>
<!ELEMENT section (iri,(questionList|infoList)+)>
<!ELEMENT iri (#PCDATA)>
<!ELEMENT questionList (question+)>
<!ELEMENT infoList (info+)>
<!ELEMENT question (iri,questionList*)>
<!ELEMENT info (#PCDATA)>
<!ATTLIST binding id ID #IMPLIED>
<!ATTLIST info type (none|checkbox|checkboxhorizontal|text|textarea|dropdown) #IMPLIED>
<!ATTLIST info property CDATA #IMPLIED>
<!ATTLIST info required (true|false) #IMPLIED>
<!ATTLIST question type (none|checkbox|checkboxhorizontal|text|textarea|dropdown) #IMPLIED>
<!ATTLIST question numbered (true|false) #IMPLIED>
<!ATTLIST question required (true|false) #IMPLIED>
<!ATTLIST question showSubquestionsForAnswer CDATA #IMPLIED>
<!ATTLIST question hideSubquestionsForAnswer CDATA #IMPLIED>
<!ATTLIST question optionOrder CDATA #IMPLIED>
<!ATTLIST section numbered (true|false) #IMPLIED>
<!ATTLIST section type (patient_section|question_section|physician_section) #IMPLIED>
<!ATTLIST questionList type (normal|inline) #IMPLIED>
<!ATTLIST ontology iri CDATA #IMPLIED>
<!ATTLIST file title CDATA #IMPLIED>

=== dfornika/facsimile/conf/conf-example.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE configuration SYSTEM "conf.dtd">
<configuration>
	<input>
		<ontology>ontology/example.owl</ontology>
	</input>
	<output>
		<file title="Example Form"/>
		<cssstyle>bmir-style</cssstyle>
	</output>
	<bindings>
		<!-- question and section classes bindings -->
		<classBindings>
			<binding id="data">http://purl.org/facsimile/example#AnnotatedData</binding>
			<binding id="data_element">http://purl.org/facsimile/example#DataValue</binding>
			<binding id="form_data">http://purl.org/facsimile/example#FormData</binding>
			<binding id="question_section">http://purl.org/facsimile/example#Observation</binding>
			<binding id="patient_section">http://purl.org/facsimile/example#UserInformation</binding>
		</classBindings>		
		<propertyBindings>
			<!-- global property bindings -->
			<binding id="has_component">http://purl.org/facsimile/example#hasComponent</binding>
			<binding id="has_form">http://purl.org/facsimile/example#hasForm</binding>
			<binding id="has_date">http://purl.org/facsimile/example#hasDate</binding>
			<!-- question property bindings -->
			<binding id="questiontext">http://purl.org/facsimile/example#hasText</binding>
			<binding id="questionfocus">http://purl.org/facsimile/example#hasFocus</binding>
			<binding id="questionvalue">http://purl.org/facsimile/example#hasValue</binding>
			<binding id="questiondatavalue">http://purl.org/facsimile/example#hasDataValue</binding>
			<!-- section property bindings -->
			<binding id="sectionheading">http://purl.org/facsimile/example#hasHeading</binding>
			<binding id="sectiontext">http://purl.org/facsimile/example#hasText</binding>
			<!-- output bindings -->
			<binding id="is_answer_to">http://purl.org/facsimile/example#isResponseTo</binding>
			<binding id="has_answer">http://purl.org/facsimile/example#hasAnswer</binding>
		</propertyBindings>
		<questionTypeBindings>
			<binding id="textarea">http://purl.org/facsimile/example#StringValue</binding>
			<binding id="radio">http://purl.org/facsimile/example#BooleanValue</binding>
			<binding id="bool_true">http://purl.org/facsimile/example#Yes</binding>
			<binding id="bool_false">http://purl.org/facsimile/example#No</binding>
		</questionTypeBindings>	
	</bindings>
	<form>
		<iri>http://purl.org/facsimile/example#user_info_form</iri>
		<section numbered="false" type="patient_section">
			<iri>http://purl.org/facsimile/example#user_details</iri>
			<infoList>
				<info type="text" property="http://purl.org/facsimile/example#hasUserName" required="true"/>
				<info type="text" property="http://purl.org/facsimile/example#hasID" required="true"/>
			</infoList>
		</section>
		<section>
			<iri>http://purl.org/facsimile/example#section_1</iri>
			<questionList>
				<question required="true" showSubquestionsForAnswer="http://purl.org/facsimile/example#Yes">
					<iri>http://purl.org/facsimile/example#question_s1_q1</iri>
					<questionList>
						<question type="text" numbered="false">
							<iri>http://purl.org/facsimile/example#question_s1_q1_1</iri>
						</question>
						<question numbered="false">
							<iri>http://purl.org/facsimile/example#question_s1_q1_2</iri>
						</question>
					</questionList>
				</question>
				<question hideSubquestionsForAnswer="http://purl.org/facsimile/example#No">
					<iri>http://purl.org/facsimile/example#question_s1_q2</iri>
					<questionList>
						<question showSubquestionsForAnswer="http://purl.org/facsimile/example#Yes">
							<iri>http://purl.org/facsimile/example#question_s1_q2_1</iri>
							<questionList>
								<question>
									<iri>http://purl.org/facsimile/example#question_s1_q2_1_1</iri>
								</question>
							</questionList>
						</question>
					</questionList>
				</question>
			</questionList>
		</section>
		<section>
			<iri>http://purl.org/facsimile/example#section_2</iri>
			<questionList>
				<question type="checkbox" showSubquestionsForAnswer="http://purl.org/facsimile/example#very_hard" optionOrder="4;1;3;2;5">
					<iri>http://purl.org/facsimile/example#question_s2_q1</iri>
					<questionList>
						<question>
							<iri>http://purl.org/facsimile/example#question_s2_q1_1</iri>
						</question>
					</questionList>
				</question>
				<question type="checkboxhorizontal" showSubquestionsForAnswer="http://purl.org/facsimile/example#not_satisfied" optionOrder="3;2">
					<iri>http://purl.org/facsimile/example#question_s2_q2</iri>
					<questionList>
						<question>
							<iri>http://purl.org/facsimile/example#question_s2_q2_1</iri>
						</question>
					</questionList>
				</question>
				<question optionOrder="3;*;4">
					<iri>http://purl.org/facsimile/example#question_s2_q3</iri>
				</question>
			</questionList>
		</section>
	</form>
</configuration>
